name: twenty

services:
  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kbdDy74IBDfMOLrvhwsBLq8wDcG0TQHR
      POSTGRES_DB: default
    healthcheck:
      test: pg_isready -U postgres -h localhost -d default
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis:alpine
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  init:
    image: twentycrm/twenty:${TAG:-v0.52.6}
    command: |
      sh -c "
        echo 'Installing PostgreSQL client...'
        apt-get update && apt-get install -y postgresql-client || true
        echo 'Waiting for database...'
        until pg_isready -h db -U postgres -d default; do
          sleep 1
        done
        echo 'Creating schemas...'
        PGPASSWORD=kbdDy74IBDfMOLrvhwsBLq8wDcG0TQHR psql -h db -U postgres -d default -c 'CREATE SCHEMA IF NOT EXISTS core; CREATE SCHEMA IF NOT EXISTS metadata;' || true
        echo 'Running migrations...'
        yarn database:migrate:prod || true
        echo 'Init completed!'
      "
    environment:
      PG_DATABASE_URL: postgres://postgres:kbdDy74IBDfMOLrvhwsBLq8wDcG0TQHR@db:5432/default
      POSTGRES_PASSWORD: kbdDy74IBDfMOLrvhwsBLq8wDcG0TQHR
      REDIS_URL: redis://redis:6379
      APP_SECRET: A2FFVimBYYdHZ3KBSfWDMKzXTWAVTD3dax2NNyBARlfzAVdcCZz3bjoKRSnpeqtO
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"

  server:
    image: twentycrm/twenty:${TAG:-v0.52.6}
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
    environment:
      SERVICE_FQDN_SERVER_3000: https://y0kswk8k4k88cwsg4ggs4404.recreabox.com
      NODE_PORT: 3000
      SERVER_URL: https://y0kswk8k4k88cwsg4ggs4404.recreabox.com
      FRONT_BASE_URL: https://y0kswk8k4k88cwsg4ggs4404.recreabox.com
      PG_DATABASE_URL: postgres://postgres:kbdDy74IBDfMOLrvhwsBLq8wDcG0TQHR@db:5432/default
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORAGE_TYPE: redis
      APP_SECRET: A2FFVimBYYdHZ3KBSfWDMKzXTWAVTD3dax2NNyBARlfzAVdcCZz3bjoKRSnpeqtO
      ACCESS_TOKEN_SECRET: cE3iI2QN3RAgxauOCT0fZv2RK0Mn1DxC
      LOGIN_TOKEN_SECRET: KR0rV28t50jX34xN5ILy2C5bwFfDZsKG
      REFRESH_TOKEN_SECRET: 2T9g94jmZ2hxMjwRlbT1zNc170rSTsoK
      FILE_TOKEN_SECRET: 9jV6vnv7gzcWkXBW3fz587S4yH2MqzGl
      ENABLE_DB_MIGRATIONS: false
      DISABLE_DB_MIGRATIONS: true
      STORAGE_TYPE: local
      API_RATE_LIMITING_TTL: 100
      API_RATE_LIMITING_LIMIT: 100
      IS_MULTIWORKSPACE_ENABLED: false
      IS_SIGN_UP_DISABLED: false
    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always

  worker:
    image: twentycrm/twenty:${TAG:-v0.52.6}
    volumes:
      - server-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://postgres:kbdDy74IBDfMOLrvhwsBLq8wDcG0TQHR@db:5432/default
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_STORAGE_TYPE: redis
      APP_SECRET: A2FFVimBYYdHZ3KBSfWDMKzXTWAVTD3dax2NNyBARlfzAVdcCZz3bjoKRSnpeqtO
      ACCESS_TOKEN_SECRET: cE3iI2QN3RAgxauOCT0fZv2RK0Mn1DxC
      LOGIN_TOKEN_SECRET: KR0rV28t50jX34xN5ILy2C5bwFfDZsKG
